engines:
  # ... CONFIG CONTENT ...
  fixme:
    enabled: true
    # ... CONFIG CONTENT ...
    exclude_fingerprints:
    - cf6190ae3ec610c9487b09c9f06391c1
  pmd:
    enabled: true
  checkstyle:
    enabled: true
