language: java
#install: ant deps

script: build.sh

env:
  global:
    - REPO="adudek/ic-depress"
    - CI_HOME=`pwd`/$REPO/ic-depress-data-anonymisation

language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

branches:
  only:
    - dev
