language: java
env:
  global:
    - REPO="adudek/ic-depress"
    - CI_HOME=`pwd`/$REPO/ic-depress/ic-depress-data-anonymisation

script: build.sh

jlanguage: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

branches:
  only:
    - dev
